baseURL = "https://example.com"
languageCode = "en-us"
title = "Hi, I am Nishant J."
theme = "cactus"
copyright = "Nishant" # cactus will use title if copyright is not set
disqusShortname = "nshantj"
googleAnalytics = "G-23LXF8HW7B"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "About Me"
url = "/about"
weight = 4

[[menu.main]]
name = "Talks"
url = "/talks"
weight = 4

[[menu.main]]
name = "My CVE(s)"
url = "/cve"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4
  [markup.goldmark.renderer] 
    unsafe= true

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # Home page settings
  description = "These are some of my notes and learnings. Trying to secure one application at a Time. The website uses [cactus hugo them](https://github.com/probberechts/hexo-theme-cactus)."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  showNotesList = true
  projectsUrl = "https://github.com/realarcherl" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/realarcherl"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/nkjj/"
  #[[params.social]]
    # name = "email"
    # link = "realarcherl@wearehackerone.com"  # no need for "mailto:" in the head
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/realArcherL"
